### PR TITLE
Updated CMake files to specify which version of OpenCV to use.

### PR DESCRIPTION
**Pull request by eshort**
Hi all,
This change just fixes the CMake files to specify using OpenCV 3.  This is necessary for machines (such as mine) with more than one version of OpenCV installed.
Best,
Elaine

### CODE REVIEW

**Comment by eshort** [comment]
Does anyone know why the travis test is failing on installing dependencies? It looks like the error has nothing to do with the changes I made, but maybe I'm reading it wrong.

**Comment by vchu** [comment]
I think I saw this error a week or so ago on another repo as well. Someone needs to go in and see why the specific package dependency doesn't install correctly anymore

**Comment by eshort** [comment]
Good to know it's at least not my changes! I'll poke around a bit and see if I can't figure out what's going on.

**Comment by eshort** [comment]
@vchu I fixed the travis problem in the master branch (sorry I didn't use a PR; I had some git... challenges, ha).  Is there anywhere else it needs to be fixed?

**Comment by vchu** [comment]
No worries at all. The fix will unfortunately have to make it to several of the HLP-R repos. If you could go through each of the HLP-R repos and see which ones have travis tests set up. They will all need to be fixed...

Thanks!

**Pull request merged**
